= This SandBox is an easy way to test CDI 1.0 features with different implementation

Thanks to Arquillian you can launch these test against :

* JBoss Weld 1.1.5 (version included in Jboss AS 7.1.1)
* Apache OpenWebBeans 1.2.6 (version included in TomEE 1.6.0)
* JBoss Weld 2.2.6 (version included in WildFly 8.2.0.Final)
* Apache OpenWebBeans 1.5.0-SNAPSHOT
* JBoss Wildfly 8.2.0 server

== Requirements

You'll need JDK 1.7 and Maven 3.x to launch these tests

== Launching test

You'll only need to choose of tof the provided maven profiles for test. Profiles are :

* `weld-1.1` for Weld 1.1.x tests
* `owb-1.2` for OpenWebBeans 1.2.x tests
* `owb-1.5` for OpenWebBeans 1.5.x tests
* `weld-2.2` for Weld 2.2.x tests
* `wildfly-8` for Wildlfy 8.x tests

Just launch `mvn clean test -P&lt;profile&gt;` to launch test (for instance `mvn clean test -Powb-1.2` to test against OpenWebBeans).
Tests won't be launched without one of these profiles.

== CDI 1.2

Checkout branch CDI-1.2 of this repository to get version of these example for CDI 1.2 (and more example not CDI 1.0 compatible)
